/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sai628_jnilib_StringUtil */

#ifndef _Included_com_sai628_jnilib_StringUtil
#define _Included_com_sai628_jnilib_StringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sai628_jnilib_StringUtil
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sai628_jnilib_StringUtil_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_sai628_jnilib_StringUtil
 * Method:    callJavaStaticMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sai628_jnilib_StringUtil_callJavaStaticMethod
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sai628_jnilib_StringUtil
 * Method:    callJavaMethod
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sai628_jnilib_StringUtil_callJavaMethod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
